config/routes.rb
Rails.application.routes.draw do
  get 'times/index'
  get 'codes/create'
  get 'codes/index'
  get 'codes/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
  
  root to: 'homes#top'
  
  get 'black_jack' => 'homes#black_jack', as: "black_jack"
  get 'scroll_anime' => 'homes#scroll_anime', as: "scroll_anime"
  
  resources :lists , only:[:create, :index, :destroy]
  resources :codes , only:[:create, :index, :destroy]
  resources :times , only:[:index] do
    collection do
      get 'experiments'
      get 'stopwatch'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
    
    validates :body, presence: true, uniqueness: true, length: { minimum: 1, maximum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
    
    validates :body, presence: true, uniqueness: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
    def index
        @code = Code.new
        @codes = Code.all
    end
    
    def create
        @codes = Code.all
        @code = Code.new(code_params)
        if @code.save
            redirect_to codes_path
        else
            render :index
        end
    end
    
    def destroy
        code = Code.find(params[:id])
        code.destroy
        redirect_to codes_path
    end
    
    
    private
    
    def code_params
        params.require(:code).permit(:body)
    end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
    def top
    end
    
    def black_jack
    end
    
    def scroll_anime
    end
    
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @list = List.new
        @lists = List.all
    end
    
    def create
        @lists = List.all
        @list = List.new(list_params)
        if @list.save
            redirect_to lists_path
        else
            render :index
        end
    end
    
    def destroy
        list = List.find(params[:id])
        list.destroy
        redirect_to lists_path
    end
    
    
    private
    
    def list_params
        params.require(:list).permit(:body)
    end
    
    
end

app/controllers/times_controller.rb
class TimesController < ApplicationController
  def index
  end
  
  def experiments
  end
  
  def stopwatch
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/times_helper.rb
module TimesHelper
end

app/views/codes/index.html.erb
<%= javascript_pack_tag 'scripts/codes_script.js', defer: true %>
<!--コンテンツ部分-->
<div id="contents">
    <h1>実験ページ：Code/index</h1>
    <%= link_to "Topに戻る", root_path %>
    <p>入力した色が存在すればボックスの色が変わります</br>履歴を押すとその色に変化します</br>カラーコード（#除く6桁）の16進数で記入してください</p>
    <p id="color_info"></p>
    <div id="box"></div>
    
    <div id="code_contents">
        <% if @code.errors.any? %>
            <ul>
                <% @code.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
        
        <%= form_with model: @code, url: codes_path do |f| %>
            <%= f.text_area :body, id: "input_data" %>
            <%= f.submit "保存" %>
        <% end %>
        
        
        <table class="container-fluid">
            <thead>
                <tr class="row-fluid">
                    <th>保存履歴</th><th></th>
                </tr>
            </thead>
            <tbody>
                <% @codes.each do |code| %>
                <tr class="row-fluid">
                    <td><p class="color_log"><%= code.body %></p></td><td><%= link_to "削除", code_path(code.id), method: :delete %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
        
    </div>
    
</div>

app/views/homes/black_jack.html.erb
<%= javascript_pack_tag 'scripts/bj_script.js', defer: true %>

<!--コンテンツ部分-->
<div id="contents">
    <%= link_to "Topに戻る", root_path %>
    <h1>実験ページ：ブラックジャック</h1>
    <p>説明：カードの合計値が21に近いほうが勝ち。21を超えると失格。</p>
    <p>説明：エリアの下部に引かれたカードの数字が表示されます。</p>
    <div id="game">
        <div id="d_area" class="area">
            <p>ディーラーエリア<span id="d_win"></span></p>
            <p id="d_card"></p>
            <p id="d_info"></p>
        </div>
        <div>VS</div>
        <div id="p_area" class="area">
            <p>プレイヤーエリア<span id="p_win"></span></p>
            <p id="p_card"></p>
            <p id="p_info"></p>
        </div>
        
        <p id="info">ゲームを開始するには開始ボタンをクリック</p>
        
        <div id="p_start">
            <button id="btn_st">開始</button>
        </div>
        
        <div id="p_select" class="hide">
            <button id="btn_hit">ヒットする</button>
            <button id="btn_ck">チェックする</button>
        </div>
        
        <button id="btn_reset" class="hide">リセットする</button>
    </div>
    
</div>

app/views/homes/scroll_anime.html.erb
<%= javascript_pack_tag 'scripts/s_anime_script.js', defer: true %>
<!--コンテンツ部分-->
<div id="contents">
    <h1>実験ページ：スクロールアニメーション</h1>
    <%= link_to "Topに戻る", root_path %>
    <div id="s_contents">
        <p class="scroll_info">下にスクロール</p>
        
        <div class="space"></div>
        
        <img src="/assets/sample-A.jpg" class="sa_image1">
        
        <div class="space"></div>
        
        <img src="/assets/sample-B.jpg" class="sa_image2">
        
        <div class="space"></div>
        
        <img src="/assets/sample-C.jpg" class="sa_image3">
    </div>
</div>

app/views/homes/top.html.erb
<%= javascript_pack_tag 'scripts/top_script.js', defer: true %>
<!--ローディング画面-->
<div id="loading_image_top">
    <h1 class="l_title">Now loading...</h1>
    <div id="l_bar"></div>
</div>


<!--コンテンツ部分-->
<div id="contents" class="hide_top">
    <h1>実験ページ：トップ</h1>
    
    <div>
        <%= link_to black_jack_path do %>
            <div>"ブラックジャックはこちら"</div>
        <% end %>
        <%= link_to scroll_anime_path do %>
            <div>"スクロールアニメーションはこちら"</div>
        <% end %>
        <%= link_to lists_path do %>
            <div>"データ保存テスト(色の名前)はこちら"</div>
        <% end %>
        <%= link_to codes_path do %>
            <div>"データ保存テスト(カラーコード)はこちら"</div>
        <% end %>
        <%= link_to times_path do %>
            <div>"時刻取得テストはこちら"</div>
        <% end %>
        <%= link_to experiments_times_path do %>
            <div>"時刻利用のアニメーションテストはこちら"</div>
        <% end %>
        <%= link_to stopwatch_times_path do %>
            <div>"ストップウォッチテストはこちら"</div>
        <% end %>
    </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebappTraining</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= javascript_pack_tag 'scripts/list_index_script.js', defer: true %>
<!--コンテンツ部分-->
<div id="contents">
    <h1>実験ページ：List/index</h1>
    <%= link_to "Topに戻る", root_path %>
    <p>入力した色が存在すればボックスの色が変わります</br>履歴を押すとその色に変化します</br>英語で記入してください</p>
    <p id="color_info"></p>
    <div id="box"></div>
    
    <div id="list_contents">
        <% if @list.errors.any? %>
            <ul>
                <% @list.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
        
        <%= form_with model: @list, url: lists_path do |f| %>
            <%= f.text_area :body, id: "input_data" %>
            <%= f.submit "保存" %>
        <% end %>
        
        
        <table class="container-fluid">
            <thead>
                <tr class="row-fluid">
                    <th>保存履歴</th><th></th>
                </tr>
            </thead>
            <tbody>
                <% @lists.each do |list| %>
                <tr class="row-fluid">
                    <td><p class="color_log"><%= list.body %></p></td><td><%= link_to "削除", list_path(list.id), method: :delete %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
        
    </div>
    
</div>

app/views/times/experiments.html.erb
<%= javascript_pack_tag 'scripts/time_experiments_script.js', defer: true %>
<!--コンテンツ部分-->
<div id="contents">
    <h1>実験ページ：Time/experiments</h1>
    <%= link_to "Topに戻る", root_path %>
    <h2>現在日時</h2>
    <p id="date"></p>
    
    
    <h2>現在時刻</h2>
    <p id="clock"></p>
    
    <button id="start_btn" class="btn">Start</button>
    <div>
        <div class="form">
            <input type="text" id="color_input" value="#aaaaaa" placeholder="値を入力">
            <p>#から始まるカラーコード（またはcssでの色の名前）を入力</p>
        </div>
        <div class="form">
            <input type="text" id="size_input" value="150" placeholder="値を入力">
            <p>文字の大きさを入力</p>
        </div>
        <div class="form">
            <input type="text" id="duration_input" value="5000" placeholder="値を入力">
            <p>スピード（ミリ秒）を入力</p>
        </div>
    </div>
    
    
    <div id='area'>
        <p id="signage"></p>
    </div>
    
    
</div>

app/views/times/index.html.erb
<%= javascript_pack_tag 'scripts/time_script.js', defer: true %>
<!--コンテンツ部分-->
<div id="contents">
    <h1>実験ページ：Time/index</h1>
    <%= link_to "Topに戻る", root_path %>
    <h2>現在日時</h2>
    <p id="date"></p>
    
    
    <h2>現在時刻</h2>
    <p id="clock"></p>
    
    <div id="c_clocks">
        <!--円（時）-->
        <div class="clock">
            <svg class="circle" viewBox="0 0 100 100">
                <circle id="c_hours" class="" cx="50%" cy="50%" r="35"></circle>
            </svg>
            <p class="info">hour</p>
        </div>
        
        <!--円（分）-->
        <div class="clock">
            <svg class="circle" viewBox="0 0 100 100">
                <circle id="c_minutes" cx="50%" cy="50%" r="35"></circle>
            </svg>
            <p class="info">minute</p>
        </div>
        
        <!--円（秒）-->
        <div class="clock">
            <svg class="circle" viewBox="0 0 100 100">
                <circle id="c_seconds" cx="50%" cy="50%" r="35"></circle>
            </svg>
            <p class="info">second</p>
        </div>
    </div>
    
    <div id="analogue_clocks" class="clock">
        <!--アナログ-->
        <div id="analogue_hour">
            <div id="a_hours"></div>
            <div id="a_minutes"></div>
            <div id="a_seconds"></div>
        </div>
    </div>
    <p class="info">Analogue</p>
    
</div>

app/views/times/stopwatch.html.erb
<%= javascript_pack_tag 'scripts/stopwatch_script.js', defer: true %>
<!--コンテンツ部分-->
<div id="contents">
    <h1>実験ページ：Time/stopwatch</h1>
    <%= link_to "Topに戻る", root_path %>
    <h2>現在日時</h2>
    <p id="date"></p>
    
    
    <h2>現在時刻</h2>
    <p id="clock"></p>
    
    <div id="s_w">
        <h2>ストップウォッチ</h2>
        <p id="show_time" class="display">00:00.000</p>
        <button id="s_btn">スタート・ストップ</button>
        <button id="r_btn" disabled>リセット</button>
    </div>
    
    
    <div id="tm">
        <h2>タイマー</h2>
        <!--stepは最小単位、valueは初期値-->
        <div id="t_input">
            <input type="number" id="i_minutes" max="59" min="0" step="1" value="00" class="display">
            <p class="display">:</p>
            <input type="number" id="i_seconds" max="59" min="0" step="1" value="00" class="display">
        </div>
        
        <div id="t_display">
            <p id="t_minutes" class="display">00</p><p class="display">:</p><p id="t_seconds" class="display">00</p>
        </div>
        <p id="t_info"></p>
        <button id="set_btn">セット</button>
        <button id="s_btn2">スタート・ストップ</button>
        <button id="r_btn2" disabled>リセット</button>
    </div>
    
</div>